<?php

(!defined('SDG')) ? die ('Triple protection!') : null;

#SYSTEM DICTIONARYS#
$arrSysDict = array('Currency' => array('type' => 'index', 'discription' => 'Currencies', 'values' => array('Ignore', 'UAH', 'USD', 'EUR')), 'Gender' => array('type' => 'assoc', 'discription' => 'Sexual identity', 'values' => array('none' => 'Ignore', 'male' => 'Male', 'female' => 'Female')), 'ActPeriod' => array('type' => 'assoc', 'discription' => 'Periods ad', 'values' => array('14' => '14 Days ', '21' => '21 Day', '30' => '30 Days ', '45' => '45 Days')), 'SearchPeriod' => array('type' => 'assoc', 'discription' => 'Periods search ads', 'values' => array('0' => 'Today', '1' => 'Yesterday', '7' => 'Over the last 7 days', '30' => 'Month', '45' => 'All Time')), 'FeedbackSubject' => array('type' => 'index', 'discription' => 'Topics Posts feedback', 'values' => array('Questions about the acquisition of the script', 'Questions on the script', 'Alert Notification of a script', 'Common questions to the developers')), 'AnnounceRecords' => array('type' => 'index', 'discription' => 'Number of ads per page', 'values' => array('5', '10', '20', '30', '40', '50')), 'SubscriptionPeriod' => array('type' => 'assoc', 'discription' => 'Periods of subscription on new ads', 'values' => array('1' => 'Daily', '3' => 'Times in 3 days', '7' => 'Times a week', '365' => 'Once a year')));
#END SYSTEM DICTIONARYS#

#ADDITIONAL DICTIONARYS#
$arrAddDict = array('ChartWork' => array('type' => 'index', 'discription' => 'Working Schedule', 'values' => array('Ignore', 'Full Day', 'In shifts', 'Free schedule')), 'Education' => array('type' => 'index', 'discription' => 'Education', 'values' => array('Ignore', 'Average-Base', 'High-School', 'Vocational', 'Higher incomplete', 'Higher Education', 'Higher baseline [BA]', 'Higher special [Engineer]', 'Higher full [Magistracy]')), 'EducationType' => array('type' => 'index', 'discription' => 'Types of Education', 'values' => array('Vocational', 'Second Higher Education', 'Professional Development/Refresher courses', 'Tests/Attestation', 'Exam/Certification')), 'Languages' => array('type' => 'index', 'discription' => 'Languages', 'values' => array('Russian', 'Ukrainian', 'English', 'German', 'French', 'Hebrew', 'Spanish', 'Italian', 'Japanese', 'Chinese', 'Sanskrit')), 'LangDegree' => array('type' => 'index', 'discription' => 'Degrees of language skills', 'values' => array('Basic', 'Elementary', 'Pre Intermediate', 'Intermediate', 'Upper Intermediate', 'Advanced', 'Expert')), 'Month' => array('type' => 'assoc', 'discription' => 'Months of the Year', 'values' => array('01' => 'January', '02' => 'February', '03' => 'March', '04' => 'April', '05' => 'May', '06' => 'June', '07' => 'July', '08' => 'August', '09' => 'September', '10' => 'October', '11' => 'November', '12' => 'December')), 'ExpireWorkSearch' => array('type' => 'index', 'discription' => 'Experience - Search', 'values' => array('Ignore', 'No experience', 'Not need', 'Required', 'From one year', 'From two years', 'More than five years')), 'ExpireWorkResume' => array('type' => 'index', 'discription' => 'Experience - Resumes', 'values' => array('No experience', 'From one year', 'From two years', 'More than five years')), 'ExpireWorkVacancy' => array('type' => 'index', 'discription' => 'Experience - Vacancys', 'values' => array('Not need', 'Required', 'From one year', 'From two years', 'More than five years')));
#END ADDITIONAL DICTIONARYS#
