<?php

(!defined('SDG')) ? die ('Triple protection!') : null;

define("CONF_ARTICLES_PERPAGE", "15");

define("CONF_ARTICLES_ADD_SUCCESS_ADMIN_INFORM", "1");

define("CONF_ARTICLES_ADD_MODERATION_ADMIN_INFORM", "1");

define("CONF_ARTICLES_CORRECTION_THERM", "72");

define("CONF_ARTICLES_COMMENTS", 1);

define("CONF_ARTICLES_COMMENTS_REGISTER", 0);

define("CONF_ARTICLES_COMMENTS_NAME_UNREGISTER", "Guest");

define("CONF_ARTICLES_TITLE_SECTION_SITE", 0);

define("CONF_ARTICLES_TITLE_SECTION_ARTICLE", 1);

define("CONF_ARTICLES_TITLE_ARTICLE_NAME", 1);
