<?php

(!defined('SDG')) ? die ('Triple protection!') : null;

define("CONF_ANNOUNCE_USER_AGREEMENT_NOMEMBERS_REQUIRED", 1);

define("CONF_ANNOUNCE_ADD_SUCCESS_ADMIN_INFORM", 1);

define("CONF_ANNOUNCE_ADD_SUCCESS_USER_INFORM", 1);

define("CONF_ANNOUNCE_USE_VISUAL_EDITOR", 1);

define("CONF_ANNOUNCE_PREVIEW", 1);

define("CONF_ANNOUNCE_PERPAGE_SITE", 6);

define("CONF_ANNOUNCE_PERPAGE_ADMIN_PANEL", 15);

define("CONF_CATEGORY_PERLINE", 2);

define("CONF_EMAIL_ATTACHMENT_FILES_ALLOW", 1);

define("CONF_EMAIL_ATTACHMENT_MAX_FILES", 1);

define("CONF_EMAIL_ATTACHMENT_FILE_MAX_SIZE", 1024);

define("CONF_VACANCY_ACTIVATE_THERM", 72);

define("CONF_VACANCY_CORRECTION_THERM", 72);

define("CONF_VACANCY_PAYMENT_THERM", 72);

define("CONF_VACANCY_VIP_THERM", 1);

define("CONF_VACANCY_VIP_SHOW", 1);

define("CONF_VACANCY_VIP_SHOW_PERPAGE", 5);

define("CONF_VACANCY_HOT_THERM", 1);

define("CONF_VACANCY_HOT_SHOW_PERPAGE", 5);

define("CONF_VACANCY_LAST_SHOW", 1);

define("CONF_VACANCY_LAST_SHOW_PERPAGE", 5);

define("CONF_RESUME_ACTIVATE_THERM", 72);

define("CONF_RESUME_CORRECTION_THERM", 72);

define("CONF_RESUME_PAYMENT_THERM", 72);

define("CONF_RESUME_VIP_THERM", 1);

define("CONF_RESUME_VIP_SHOW", 1);

define("CONF_RESUME_VIP_SHOW_PERPAGE", 5);

define("CONF_RESUME_HOT_THERM", 1);

define("CONF_RESUME_HOT_SHOW_PERPAGE", 5);

define("CONF_RESUME_LAST_SHOW", 1);

define("CONF_RESUME_LAST_SHOW_PERPAGE", 5);

define("CONF_RESUME_ADD_PHOTO", 1);

define("CONF_RESUME_ADD_PHOTO_MAXWIDTH", 150);

define("CONF_RESUME_ADD_PHOTO_MAXHEIGHT", 200);

define("CONF_RESUME_ADD_PHOTO_FILE_MAXSIZE", 1024);
