<?php

(!defined('SDG')) ? die ('Triple protection!') : null;

define("CONF_SUBSCRIPTIONS_STRINGS_PERPAGE_ADMIN_PANEL", "5");

define("CONF_SUBSCRIPTIONS_FREE_VACANCY", "2");

define("CONF_SUBSCRIPTIONS_FREE_RESUME", "3");

define("CONF_SUBSCRIPTIONS_PAYMENT_DELETE", "48");

define("CONF_SUBSCRIPTIONS_ANNOUNCE_PERIOD", "3");

define("CONF_SUBSCRIPTIONS_START_TIME", 1324581927);
