--
-- Дамп данных таблицы `%DB_PREFIX%section`
--

INSERT INTO `%DB_PREFIX%section` (`id`, `name`, `sort`, `token`) VALUES
(1, 'Administrative & Service', 1, 'active'),
(2, 'Arts & Media', 2, 'active'),
(3, 'Finance', 3, 'active'),
(4, 'Government & Legal', 4, 'active'),
(5, 'Healthcare', 5, 'active'),
(6, 'Hourly & Skilled', 6, 'active'),
(7, 'Management', 7, 'active'),
(8, 'Sales & Marketing', 8, 'active'),
(9, 'Science & Technology', 9, 'active'),
(10, 'Accounting / Finance', 0, 'active');;;

--
-- Дамп данных таблицы `%DB_PREFIX%profession`
--

INSERT INTO `%DB_PREFIX%profession` (`id`, `parent_id`, `name`, `sort`, `token`) VALUES
(1, 1, 'Administrative / Clerical', 0, 'active'),
(2, 1, 'Call Center', 0, 'active'),
(3, 1, 'Customer Service', 0, 'active'),
(4, 1, 'Entry Level', 0, 'active'),
(5, 1, 'Hospitality / Hotel / Travel', 0, 'active'),
(6, 1, 'Restaurant / Food Service', 0, 'active'),
(7, 2, 'Architecture', 0, 'active'),
(8, 2, 'Arts / Media', 0, 'active'),
(9, 2, 'Decorating / Design', 0, 'active'),
(10, 2, 'Education / Teaching', 0, 'active'),
(11, 2, 'Publishing / Journalism', 0, 'active'),
(12, 2, 'Radio / Television', 0, 'active'),
(13, 3, 'Accounting / Finance', 0, 'active'),
(14, 3, 'Banking / Mortgage', 0, 'active'),
(15, 3, 'Insurance', 0, 'active'),
(16, 3, 'Non-profit / Fundraising', 0, 'active'),
(17, 4, 'Activism', 0, 'active'),
(18, 4, 'Government / Civil Service', 0, 'active'),
(19, 4, 'Law Enforcement / Security', 0, 'active'),
(20, 4, 'Legal / Law Related Military', 0, 'active'),
(21, 5, 'Healthcare / Nursing', 0, 'active'),
(22, 5, 'Pharmaceutical', 0, 'active'),
(23, 5, 'Social Services / Counseling', 0, 'active'),
(24, 6, 'Agriculture', 0, 'active'),
(25, 6, 'Airlines / Aviation', 0, 'active'),
(26, 6, 'Automotive', 0, 'active'),
(27, 6, 'Construction & Trades', 0, 'active'),
(28, 6, 'HVAC', 0, 'active'),
(29, 6, 'Industrial', 0, 'active'),
(30, 6, 'Maintenance / Facilities Management', 0, 'active'),
(31, 6, 'Manufacturing', 0, 'active'),
(32, 6, 'Mining & Metals', 0, 'active'),
(33, 6, 'Packaging', 0, 'active'),
(34, 6, 'Recreation', 0, 'active'),
(35, 6, 'Shipping & Receiving', 0, 'active'),
(36, 6, 'Transportation', 0, 'active'),
(37, 6, 'Utilities', 0, 'active'),
(38, 6, 'Warehouse / Distribution', 0, 'active'),
(39, 6, 'Waste Management', 0, 'active'),
(40, 7, 'Consulting', 0, 'active'),
(41, 7, 'Employment / Staffing', 0, 'active'),
(42, 7, 'Executive Management', 0, 'active'),
(43, 7, 'Human Resources / Training', 0, 'active'),
(44, 7, 'Management', 0, 'active'),
(45, 7, 'Purchasing / Procurement', 0, 'active'),
(46, 7, 'Real Estate / Property Management', 0, 'active'),
(47, 7, 'Supply Chain / Logistics', 0, 'active'),
(48, 8, 'Advertising / Marketing / PR', 0, 'active'),
(49, 8, 'Consumer Products', 0, 'active'),
(50, 8, 'Import / Export', 0, 'active'),
(51, 8, 'Retail / Fashion / Grocery', 0, 'active'),
(52, 8, 'Sales / Sales Management', 0, 'active'),
(53, 8, 'Telemarketing', 0, 'active'),
(54, 9, 'Aerospace / Biotechnology', 0, 'active'),
(55, 9, 'Chemical', 0, 'active'),
(56, 9, 'E-commerce', 0, 'active'),
(57, 9, 'Electronic', 0, 'active'),
(58, 9, 'Energy / Power', 0, 'active'),
(59, 9, 'Engineering', 0, 'active'),
(60, 9, 'Environmental Sciences', 0, 'active'),
(61, 9, 'Information Technology / Computer', 0, 'active'),
(62, 9, 'Internet / Web', 0, 'active'),
(63, 9, 'Research', 0, 'active'),
(64, 9, 'Science', 0, 'active'),
(65, 9, 'Telecom / Wireless / Cable', 0, 'active'),
(66, 10, 'Accounting / Finance', 0, 'active');;;


--
-- Дамп данных таблицы `%USR_PREFIX%region`
--

INSERT INTO `%USR_PREFIX%region` (`id`, `name`, `sort`, `token`) VALUES
(1, 'Baden-Wurttemberg', 1, 'active'),
(2, 'Bavaria', 2, 'active'),
(3, 'Berlin', 3, 'active'),
(4, 'Brandenburg', 4, 'active'),
(5, 'Bremen', 5, 'active'),
(6, 'Hamburg', 6, 'active'),
(7, 'Hesse', 7, 'active'),
(8, 'Lower Saxony', 8, 'active'),
(9, 'Mecklenburg-Vorpommern', 9, 'active'),
(10, 'North Rhine-Westphalia', 10, 'active'),
(11, 'Rhineland-Palatinate', 11, 'active'),
(12, 'Saarland', 12, 'active'),
(13, 'Saxony', 13, 'active'),
(14, 'Saxony-Anhalt', 14, 'active'),
(15, 'Schleswig-Holstein', 15, 'active'),
(16, 'Thuringia', 16, 'active');;;

--
-- Дамп данных таблицы `%USR_PREFIX%city`
--

INSERT INTO `%USR_PREFIX%city` (`id`, `parent_id`, `name`, `capital`, `token`) VALUES
(1, 1, 'Baden-Baden', '0', 'active'),
(2, 1, 'Freiburg', '0', 'active'),
(3, 1, 'Heidelberg', '0', 'active'),
(4, 1, 'Heilbronn', '0', 'active'),
(5, 1, 'Karlsruhe', '0', 'active'),
(6, 1, 'Mannheim', '0', 'active'),
(7, 1, 'Pforzheim', '0', 'active'),
(8, 1, 'Stuttgart', '0', 'active'),
(9, 1, 'Ulm', '0', 'active'),
(10, 2, 'Amberg', '0', 'active'),
(11, 2, 'Ansbach', '0', 'active'),
(12, 2, 'Aschaffenburg', '0', 'active'),
(13, 2, 'Augsburg', '0', 'active'),
(14, 2, 'Bamberg', '0', 'active'),
(15, 2, 'Bayreuth', '0', 'active'),
(16, 2, 'Coburg', '0', 'active'),
(17, 2, 'Erlangen', '0', 'active'),
(18, 2, 'Furth', '0', 'active'),
(19, 2, 'Hof', '0', 'active'),
(20, 2, 'Ingolstadt', '0', 'active'),
(21, 2, 'Kaufbeuren', '0', 'active'),
(22, 2, 'Kempten', '0', 'active'),
(23, 2, 'Landshut', '0', 'active'),
(24, 2, 'Memmingen', '0', 'active'),
(25, 2, 'Munich', '0', 'active'),
(26, 2, 'Nuremberg', '0', 'active'),
(27, 2, 'Passau', '0', 'active'),
(28, 2, 'Regensburg', '0', 'active'),
(29, 2, 'Rosenheim', '0', 'active'),
(30, 2, 'Schwabach', '0', 'active'),
(31, 2, 'Schweinfurt', '0', 'active'),
(32, 2, 'Straubing', '0', 'active'),
(33, 2, 'Weiden', '0', 'active'),
(34, 2, 'Wurzburg', '0', 'active'),
(35, 3, 'Berlin', '0', 'active'),
(36, 4, 'Brandenburg an der Havel', '0', 'active'),
(37, 4, 'Cottbus', '0', 'active'),
(38, 4, 'Frankfurt', '0', 'active'),
(39, 4, 'Potsdam', '0', 'active'),
(40, 5, 'Bremen', '0', 'active'),
(41, 6, 'Hamburg', '0', 'active'),
(42, 7, 'Darmstadt', '0', 'active'),
(43, 7, 'Frankfurt am Main', '0', 'active'),
(44, 7, 'Kassel', '0', 'active'),
(45, 7, 'Offenbach am Main', '0', 'active'),
(46, 7, 'Wiesbaden', '0', 'active'),
(47, 8, 'Braunschweig', '0', 'active'),
(48, 8, 'Delmenhorst', '0', 'active'),
(49, 8, 'Emden', '0', 'active'),
(50, 8, 'Gottingen', '0', 'active'),
(51, 8, 'Hannover', '0', 'active'),
(52, 8, 'Oldenburg', '0', 'active'),
(53, 8, 'Osnabruck', '0', 'active'),
(54, 8, 'Salzgitter', '0', 'active'),
(55, 8, 'Wilhelmshaven', '0', 'active'),
(56, 8, 'Wolfsburg', '0', 'active'),
(57, 9, 'Rostock', '0', 'active'),
(58, 9, 'Greifswald', '0', 'active'),
(59, 9, 'Neubrandenburg', '0', 'active'),
(60, 9, 'Schwerin', '0', 'active'),
(61, 9, 'Stralsund', '0', 'active'),
(62, 9, 'Wismar', '0', 'active'),
(63, 10, 'Cologne', '0', 'active'),
(64, 10, 'Dusseldorf', '0', 'active'),
(65, 10, 'Dortmund', '0', 'active'),
(66, 10, 'Essen', '0', 'active'),
(67, 10, 'Duisburg', '0', 'active'),
(68, 10, 'Bochum', '0', 'active'),
(69, 10, 'Wuppertal', '0', 'active'),
(70, 10, 'Bielefeld', '0', 'active'),
(71, 10, 'Bonn', '0', 'active'),
(72, 10, 'Munster', '0', 'active'),
(73, 11, 'Frankenthal', '0', 'active'),
(74, 11, 'Kaiserslautern', '0', 'active'),
(75, 11, 'Koblenz Coblenz', '0', 'active'),
(76, 11, 'Landau', '0', 'active'),
(77, 11, 'Ludwigshafen', '0', 'active'),
(78, 11, 'Mainz', '0', 'active'),
(79, 11, 'Neustadt', '0', 'active'),
(80, 11, 'Pirmasens', '0', 'active'),
(81, 11, 'Speyer Spires', '0', 'active'),
(82, 11, 'Trier', '0', 'active'),
(83, 11, 'Worms', '0', 'active'),
(84, 11, 'Zweibrucken', '0', 'active'),
(85, 12, 'Merzig-Wadern', '0', 'active'),
(86, 12, 'Neunkirchen', '0', 'active'),
(87, 12, 'Saarbrucken', '0', 'active'),
(88, 12, 'Saarlouis', '0', 'active'),
(89, 12, 'Saarpfalz', '0', 'active'),
(90, 12, 'Sankt Wendel', '0', 'active'),
(91, 13, 'Chemnitz', '0', 'active'),
(92, 13, 'Dresden', '0', 'active'),
(93, 13, 'Leipzig', '0', 'active'),
(94, 14, 'Dessau-Roblau', '0', 'active'),
(95, 14, 'Halle', '0', 'active'),
(96, 14, 'Magdeburg', '0', 'active'),
(97, 15, 'Kiel', '0', 'active'),
(98, 15, 'Hansestadt', '0', 'active'),
(99, 15, 'Neumunster', '0', 'active'),
(100, 15, 'Flensburg', '0', 'active'),
(101, 16, 'Erfurt', '0', 'active'),
(102, 16, 'Eisenach', '0', 'active'),
(103, 16, 'Gera', '0', 'active'),
(104, 16, 'Jena', '0', 'active'),
(105, 16, 'Suhl', '0', 'active'),
(106, 16, 'Weimar', '0', 'active');;;