<?php 
define("TB_BROWSE", "Обзор");
define("TB_CONTROL", "Управление");
define("TB_UPLOAD", "Загрузка");
define("TB_FOLDERS", "Папки");
define("TB_FOLDERNAME", "Имя папки");
define("TB_FOLDERCURR", "Текущая папка: ");
define("TB_FOLDERDEST", "В папку: ");
define("TB_VIEW", "Вид: ");
define("TB_SHOW", "Просмотр: ");
define("TB_PAGE", "Страница");
define("TB_FILENAME", "Имя файла");
define("TB_SIZE", "Объем");
define("TB_DIMENSIONS", "Размеры");
define("TB_TYPE", "Тип");
define("TB_DATE", "Дата");
define("TB_SEARCH", "Поиск");
define("TB_FILES", "Файлы");
define("TB_BROWSEFILES", "Обзор файлов");
define("TB_DETAILS", "Таблица");
define("TB_THUMBS", "Эскизы");
define("TB_CONTROLFILES", "Управление файлами");
define("TB_ACTION", "Действие: ");
define("TB_CREATE", "Создать");
define("TB_DELETE", "Удалить");
define("TB_RENAME", "Переименовать");
define("TB_ROTATE", "Повернуть");
define("TB_RESIZE", "Размеры");
define("TB_MOVE", "Переместить");
define("TB_UPLOADFILES", "Загрузка файлов");
define("TB_PROGRESS", "Прогресс");
define("TB_REMOVE", "Удалить");
define("TB_BYTES", "байт");
define("TB_WIDTH", "ширина");
define("TB_HEIGHT", "высота");
define("TB_NONE", "НЕТ");
define("TB_TYPEIMG", "Изображения");
define("TB_TYPEMEDIA", "Медиа");
define("TB_TYPEFILE", "Все файлы");
define("TB_ROTATECW", "Повернуть на 90 градутов по часовой");
define("TB_ROTATECCW", "Повернуть на 90 градутов против часовой");
define("TB_MSGMKDIR", "Папка '%s' успешно создана.");
define("TB_MSGMKDIRFAIL", "Не удалось создать папку '%s' - пожалуйста проверьте права доступа.");
define("TB_MSGCREATE", "успешно созданы: %s.");
define("TB_MSGDELETE", "успешно удалены: %s.");
define("TB_MSGRENAME", "успешно переименованы: %s.");
define("TB_MSGMOVE", "успешно перемещены: %s.");
define("TB_MSGRESIZE", "успешно изменены размеры: %s.");
define("TB_MSGROTATE", "успешно изменены: %s.");
define("TB_MSGEDITERR", "с ошибками операции: %s.");
define("TB_MSGUPGOOD", "успешно загружены: %s.");
define("TB_MSGUPBAD", "не удалось загрузить: %s - из-за ограничений прав доступа.");
define("TB_MSGUPDUP", "дубликаты: %s - пожалуйста, сначала удалите оригиналы.");
define("TB_MSGUPFAIL", "Ошибка загрузки в: %s - пожалуйста, проверьте права доступа.");
define("TB_MSGMAXSIZE", "не могут быть поставлены в очередь для загрузки, так как размер превышает максимальный предел");
define("TB_TTLMAXSIZE", "Превышен допустимый размера файла");
define("TB_DENIED", "У Вас недостаточно прав для просмотра данной страницы.");
define("TB_UPDENIED", "Вам необходимо получить разрешение на доступ к загрузкам для просмотра данной страницы.");
define("TB_EDDENIED", "Вам необходимо  получить разрешение на изменение/удаление для просмотра данной страницы.");
define("TB_FODENIED", "Вам необходимо получить разрешение на доступ к папкам для просмотра данной страницы.");
